name: download videos

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: download

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install You-get
      id: videos
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ --debug 'https://www.youtube.com/watch?v=bD-CWgbsCeI&list=PLgKuh-lKre10UQnP7gBCFoKgq5KWIA7el'
 
        you-get -o ./you_get/ --debug 'https://www.youtube.com/watch?v=ZTxR2n2mvjc'         

        you-get -o ./you_get/ --debug 'https://www.youtube.com/watch?v=doyK1olswX4' 
        
        ls
        echo '------------------------------'
        cd you_get
        ls 
        echo '~~~~~~~~~~~~~~~~~~~~~~'
        cd ../
        mkdir awesome-quantum-machine-learning/videos
        cp -r you_get/. awesome-quantum-machine-learning/videos
        cd awesome-quantum-machine-learning/
        git config --global user.email "ucecwme@ucl.ac.uk"
        git config --global user.name "nickcafferry"
        git init
        cd videos/
        git add -A
        git status 
        git commit -m "Add some videos"
        ls
        git push origin master
