name: videos maker

on:
  push:
    branches:
      - master

jobs:
  build_docs_and_deploy:
    runs-on: ubuntu-latest
    name: videos maker

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install You-get
      run: |
        cd ..
        mkdir you_get
        ls
        echo '======================='
        pip3 install you-get
        export PATH="$PATH:/home/runner/.local/bin:/home/runner/you_get"
        you-get -o ./you_get/ --debug 'https://video.fosdem.org/2020/UA2.118/getting_started_with_quantum_software_development.mp4'
        you-get -o ./you_get/ --debug 'http://mirroronet.pl/pub/mirrors/video.fosdem.org/2020/UA2.118/kotlin_automate_your_workflows.mp4'
        you-get -o ./you_get/ --debug 'http://mirroronet.pl/pub/mirrors/video.fosdem.org/2020/UA2.118/kotlin_communication_break_down_coroutines.mp4'
        you-get -o ./you_get/ --debug 'http://mirroronet.pl/pub/mirrors/video.fosdem.org/2020/UA2.118/kotlin_confessions_of_a_multiplatformer.mp4'
        you-get -o ./you_get/ --debug 'http://mirroronet.pl/pub/mirrors/video.fosdem.org/2020/UA2.118/kotlin_designing_a_dsl.mp4'
        
        
        cd you_get/
        ls
        pwd

    - uses: actions/upload-artifact@v2
      with:
        name: quantum videos
        path: /home/runner/work/awesome-quantum-machine-learning/you_get/
        
